Fix "EACCES: permission denied error
The error below occured, because the node user is not the owner of the files in the /app folder. This is fixed by first copying the files to /app and THEN use chown.
Before this fix, the error was:

...
Step 6/9 : RUN yarn install
 ---> Running in 2a2affd4cb2b
yarn install v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
error Could not write file "/app/yarn-error.log": "EACCES: permission denied, open '/app/yarn-error.log'"
error An unexpected error occurred: "EACCES: permission denied, unlink '/app/node_modules/.yarn-integrity'".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
ERROR: Service 'server' failed to build : The command '/bin/sh -c yarn install' returned a non-zero code: 1